# .goreleaser.yml
# Build customization
builds:
  - main: cmd/main.go
binary: graphs
goos:
  - windows
  - darwin
  - linux
goarch:
  - amd64
  - arm64
# Archive customization
archive:
  format: tar.gz